# This workflow will build a project with Gradle, publish artifacts and release new version

name: "🚀 Release Artifacts"

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master" ]

jobs:

  release_artifacts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      MAVEN_SNAPSHOTS_REPOSITORY_URL: https://oss.sonatype.org/content/repositories/snapshots/
      MAVEN_RELEASES_REPOSITORY_URL: https://oss.sonatype.org/service/local/staging/deploy/maven2/
      OSS_USERNAME: ${{ secrets.OSS_USERNAME }}
      OSS_PASSWORD: ${{ secrets.OSS_PASSWORD }}

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: build

      - name: Publish artifacts
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: publishToMavenLocal
