# This workflow will build project with Gradle, publish artifacts and release new version

name: "🚀 Release Artifacts"

on:
  workflow_dispatch:

env:
  GRADLE_OPTS: -Dorg.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=512m

jobs:

  release_artifacts:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Gradle Wrapper validation
        uses: gradle/wrapper-validation-action@v1.0.6

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: clean build

      - name: Current version
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: currentVersion

      - name: Release new version
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: |
            release
            -Prelease.customUsername=${{ github.actor }}
            -Prelease.customPassword=${{ github.token }}
            -Prelease.ignoreUncommittedChanges=true
            --stacktrace

      - name: Publish artifacts
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: publishToMavenLocal --stacktrace
        env:
          OSS_USERNAME: ${{ secrets.OSS_USERNAME }}
          OSS_PASSWORD: ${{ secrets.OSS_PASSWORD }}
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
