# This workflow will build project with Gradle, publish artifacts and release new version

name: "🚀 Release Artifacts"

on:
  workflow_dispatch:

jobs:

  release_artifacts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: clean build

      - name: Publish artifacts
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: publishToMavenLocal --stacktrace
        env:
          OSS_USERNAME: ${{ secrets.OSS_USERNAME }}
          OSS_PASSWORD: ${{ secrets.OSS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.GPG_SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.GPG_SIGNING_PASSWORD }}

      - name: Release version
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: currentVersion release -Prelease.ignoreUncommittedChanges=true --stacktrace

      - name: Push tags
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git push --tags
